# Perfil exclusivo para pruebas de carga locales.
# Evita que miles de consultas SQL saturen la consola y la memoria del IDE.
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.springframework.mail=WARN
