spring.application.name=vargasvet
server.port=8080
server.servlet.context-path=/api/v1

# =========================
# DATABASE
# =========================
#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=jdbc:postgresql://dpg-d81o2f3eo5us73aep27g-a.oregon-postgres.render.com:5432/vargasvet_db
spring.datasource.username=vargasvet_db_user
spring.datasource.password=h6mrh6NBO3XDKVMIItfioIpD7tFPD2St


spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

# =========================
# JWT
# =========================
jwt.validity-in-seconds=259200
jwt.private-key=classpath:keys/private_key.pem
jwt.public-key=classpath:keys/public_key.pem

# =========================
# MAIL SMTP
# =========================
spring.mail.host=${MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

app.mail.from=${MAIL_FROM:sebastiansaavedraarroyo8@gmail.com}

spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# =========================
# APPLICATION
# =========================
app.url=${APP_URL:http://localhost:4200}
app.frontend.verify-url=${app.url}/auth/verify/
app.frontend.login-url=${app.url}/auth/login

app.company.name=Patitas Felices
app.company.email=soporte@patitasfelices.com
app.company.phone=+51 999 888 777
app.company.address=Av. Veterinaria 123, Lima, PerÃº
app.company.logo=https://i.postimg.cc/xTJ77LFz/images.png

# =========================
# FILE STORAGE
# =========================
storage.location=uploads

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# =========================
# CORS
# =========================
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://systemvetfrontend.vercel.app}

# =========================
# SWAGGER / OPENAPI
# =========================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# =========================
# LOGGING
# =========================
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.security=INFO

# =========================
# MERCADOPAGO TEST
# =========================
mercadopago.access-token=TEST-614170041567644-051716-8d2d12515d0066a3379d7b272ed74868-3408804304
mercadopago.public-key=TEST-dfc6af5a-ed42-414b-924b-7c8a9d542ae1

