spring.application.name=vargasvet
server.port=8080
server.servlet.context-path=/api/v1

# =========================
# DATABASE LOCAL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/vargasvet_db_local
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

# =========================
# JWT
# =========================
jwt.validity-in-seconds=259200
jwt.private-key=classpath:keys/private_key.pem
jwt.public-key=classpath:keys/public_key.pem

# =========================
# MAIL SMTP
# Puedes colocar tus datos reales o datos temporales para desarrollo
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=TU_CORREO_GMAIL
spring.mail.password=TU_PASSWORD_APP_GMAIL
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# =========================
# APPLICATION LOCAL
# =========================
app.url=http://localhost:4200
app.frontend.verify-url=http://localhost:4200/auth/verify/
app.frontend.login-url=http://localhost:4200/login

app.company.name=Patitas Felices
app.company.email=soporte@patitasfelices.com
app.company.phone=+51 999 888 777
app.company.address=Av. Veterinaria 123, Lima, Perú
app.company.logo=https://i.postimg.cc/xTJ77LFz/images.png

# =========================
# FILE STORAGE
# =========================
storage.location=uploads

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# =========================
# CORS LOCAL
# =========================
cors.allowed-origins=http://localhost:4200

# =========================
# SWAGGER / OPENAPI
# =========================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# =========================
# LOGGING
# =========================
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.security=INFO

# =========================
# MERCADOPAGO TEST
# =========================
mercadopago.access-token=TEST-614170041567644-051716-8d2d12515d0066a3379d7b272ed74868-3408804304
mercadopago.public-key=TEST-dfc6af5a-ed42-414b-924b-7c8a9d542ae1
