package veterinaria.vargasvet.domain.enums;

public enum EPermission {
    USER_READ, USER_CREATE, USER_UPDATE, USER_DELETE,
    ROLE_MANAGE,
    PET_READ, PET_CREATE, PET_UPDATE, PET_DELETE,
    CLINICAL_RECORD_READ,
    CLINICAL_RECORD_MANAGE, 
    VETERINARY_PRACTICE,    

    COMPANY_MANAGE,
    SYSTEM_CONFIG,
    INVENTORY_READ, INVENTORY_MANAGE,
    SALE_READ, SALE_MANAGE,
    PURCHASE_MANAGE
}
