ALTER TABLE citas DROP CONSTRAINT IF EXISTS citas_estado_check;
ALTER TABLE citas ADD CONSTRAINT citas_estado_check CHECK (estado IN (
    'PROGRAMADA', 'PENDIENTE', 'CONFIRMADA', 'REPROGRAMADA',
    'SALA_DE_ESPERA', 'EN_PROCESO', 'COMPLETADA', 'NO_ASISTIO',
    'CANCELADA', 'ELIMINADA', 'OTRO'
));
